require "user.keymaps" 
require "user.options"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.nvim-tree"
require "user.lualine"
require "user.nvim-treesitter"
require "user.code_runner"
require "user.toggleterm"
require "user.comment"
require "user.telescope"
require "user.bufferline"
require "user.autopairs"
require "user.alpha"
-- Fundamental stuff
